# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/pasteur_wifi/setup-makefiles.sh

VENDOR_BLOB_FOLDER := vendor/motorola/pasteur_wifi/proprietary

PRODUCT_COPY_FILES += \
    $(VENDOR_BLOB_FOLDER)/lib/hw/gps.pasteur.so:system/lib/hw/gps.pasteur.so \
    $(VENDOR_BLOB_FOLDER)/lib/hw/sensors.pasteur.so:system/lib/hw/sensors.pasteur.so \
    $(VENDOR_BLOB_FOLDER)/lib/hw/lights.pasteur.so:system/lib/hw/lights.pasteur.so \
    $(VENDOR_BLOB_FOLDER)/lib/libsensorhub_jni.so:system/lib/libsensorhub_jni.so \
    $(VENDOR_BLOB_FOLDER)/etc/omapcam/module2/cid1044_mt9m114_sensor_config_dcc.bin:system/etc/omapcam/module2/cid1044_mt9m114_sensor_config_dcc.bin \
    $(VENDOR_BLOB_FOLDER)/bin/akmd8975:system/bin/akmd8975 \
    $(VENDOR_BLOB_FOLDER)/bin/ap_gain.bin:system/bin/ap_gain.bin \
    $(VENDOR_BLOB_FOLDER)/bin/ap_gain_mmul.bin:system/bin/ap_gain_mmul.bin \
    $(VENDOR_BLOB_FOLDER)/etc/firmware/ducati-m3.bin:system/etc/firmware/ducati-m3.bin \
    $(VENDOR_BLOB_FOLDER)/etc/firmware/TIInit_10.6.15.bts:system/etc/firmware/TIInit_10.6.15.bts \
    $(VENDOR_BLOB_FOLDER)/lib/hw/audio.primary.omap4.so:system/lib/hw/audio.primary.omap4.so
